#!/bin/sh
MYSQL_OPTIONS="-h $MYSQL_HOST --user=$MASTER_USER --password=$MASTER_PASSWORD"

echo "GRANT $MYSQL_PERMISSIONS ON $MYSQL_DB.* TO '$MYSQL_USER'@\`%\` IDENTIFIED BY '$MYSQL_PASSWORD';"|mysql $MYSQL_OPTIONS
